version: "3"
services:
  scrum-board-flask-api:
    build: ./
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      POSTGRES_URI: postgresql://scrum-board:scrum-board@postgres:5432/scrum-board
      JWT_SECRET_KEY: jwt_secret_key

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: scrum-board
      POSTGRES_USER: scrum-board
      POSTGRES_PASSWORD: scrum-board
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/:/var/lib/postgresql/data/